def pegar_setores():
    setores = {"Agriculture, Forestry, Fishing and Hunting" : "Agriculture, Forestry, Fishing and Hunting",
    "Oilseed and Grain Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Soybean Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Oilseed (except Soybean) Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Dry Pea and Bean Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Wheat Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Corn Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Rice Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Oilseed and Grain Combination Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "All Other Grain Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Vegetable and Melon Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Potato Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Other Vegetable (except Potato) and Melon Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Fruit and Tree Nut Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Orange Groves" : "Agriculture, Forestry, Fishing and Hunting",
    "Citrus (except Orange) Groves" : "Agriculture, Forestry, Fishing and Hunting",
    "Apple Orchards" : "Agriculture, Forestry, Fishing and Hunting",
    "Grape Vineyards" : "Agriculture, Forestry, Fishing and Hunting",
    "Strawberry Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Berry (except Strawberry) Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Tree Nut Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Fruit and Tree Nut Combination Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Other Noncitrus Fruit Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Greenhouse, Nursery, and Floriculture Production" : "Agriculture, Forestry, Fishing and Hunting",
    "Mushroom Production" : "Agriculture, Forestry, Fishing and Hunting",
    "Other Food Crops Grown Under Cover" : "Agriculture, Forestry, Fishing and Hunting",
    "Nursery and Tree Production" : "Agriculture, Forestry, Fishing and Hunting",
    "Floriculture Production" : "Agriculture, Forestry, Fishing and Hunting",
    "Other Crop Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Tobacco Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Cotton Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Sugarcane Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Hay Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Sugar Beet Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Peanut Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "All Other Miscellaneous Crop Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Cattle Ranching and Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Beef Cattle Ranching and Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Cattle Feedlots" : "Agriculture, Forestry, Fishing and Hunting",
    "Dairy Cattle and Milk Production" : "Agriculture, Forestry, Fishing and Hunting",
    "Dual-Purpose Cattle Ranching and Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Hog and Pig Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Poultry and Egg Production" : "Agriculture, Forestry, Fishing and Hunting",
    "Chicken Egg Production" : "Agriculture, Forestry, Fishing and Hunting",
    "Broilers and Other Meat Type Chicken Production" : "Agriculture, Forestry, Fishing and Hunting",
    "Turkey Production" : "Agriculture, Forestry, Fishing and Hunting",
    "Poultry Hatcheries" : "Agriculture, Forestry, Fishing and Hunting",
    "Other Poultry Production" : "Agriculture, Forestry, Fishing and Hunting",
    "Sheep and Goat Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Sheep Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Goat Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Aquaculture" : "Agriculture, Forestry, Fishing and Hunting",
    "Finfish Farming and Fish Hatcheries" : "Agriculture, Forestry, Fishing and Hunting",
    "Shellfish Farming" : "Agriculture, Forestry, Fishing and Hunting",
    "Other Aquaculture" : "Agriculture, Forestry, Fishing and Hunting",
    "Other Animal Production" : "Agriculture, Forestry, Fishing and Hunting",
    "Apiculture" : "Agriculture, Forestry, Fishing and Hunting",
    "Horses and Other Equine Production" : "Agriculture, Forestry, Fishing and Hunting",
    "Fur-Bearing Animal and Rabbit Production" : "Agriculture, Forestry, Fishing and Hunting",
    "All Other Animal Production" : "Agriculture, Forestry, Fishing and Hunting",
    "Timber Tract Operations" : "Agriculture, Forestry, Fishing and Hunting",
    "Forest Nurseries and Gathering of Forest Products" : "Agriculture, Forestry, Fishing and Hunting",
    "Logging" : "Agriculture, Forestry, Fishing and Hunting",
    "Fishing" : "Agriculture, Forestry, Fishing and Hunting",
    "Finfish Fishing" : "Agriculture, Forestry, Fishing and Hunting",
    "Shellfish Fishing" : "Agriculture, Forestry, Fishing and Hunting",
    "Other Marine Fishing" : "Agriculture, Forestry, Fishing and Hunting",
    "Hunting and Trapping" : "Agriculture, Forestry, Fishing and Hunting",
    "Support Activities for Crop Production" : "Agriculture, Forestry, Fishing and Hunting",
    "Cotton Ginning" : "Agriculture, Forestry, Fishing and Hunting",
    "Soil Preparation, Planting, and Cultivating" : "Agriculture, Forestry, Fishing and Hunting",
    "Crop Harvesting, Primarily by Machine" : "Agriculture, Forestry, Fishing and Hunting",
    "Postharvest Crop Activities (except Cotton Ginning)" : "Agriculture, Forestry, Fishing and Hunting",
    "Farm Labor Contractors and Crew Leaders" : "Agriculture, Forestry, Fishing and Hunting",
    "Farm Management Services" : "Agriculture, Forestry, Fishing and Hunting",
    "Support Activities for Animal Production" : "Agriculture, Forestry, Fishing and Hunting",
    "Support Activities for Forestry" : "Agriculture, Forestry, Fishing and Hunting",
    "Mining, Quarrying, and Oil and Gas Extraction" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Oil and Gas Extraction" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Crude Petroleum Extraction" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Natural Gas Extraction" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Coal Mining" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Surface Coal Mining" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Underground Coal Mining" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Metal Ore Mining" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Iron Ore Mining" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Gold Ore and Silver Ore Mining" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Copper, Nickel, Lead, and Zinc Mining" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Other Metal Ore Mining" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Nonmetallic Mineral Mining and Quarrying" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Dimension Stone Mining and Quarrying" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Crushed and Broken Limestone Mining and Quarrying" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Crushed and Broken Granite Mining and Quarrying" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Other Crushed and Broken Stone Mining and Quarrying" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Construction Sand and Gravel Mining" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Industrial Sand Mining" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Kaolin, Clay, and Ceramic and Refractory Minerals Mining" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Other Nonmetallic Mineral Mining and Quarrying" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Support Activities for Mining" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Drilling Oil and Gas Wells" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Support Activities for Oil and Gas Operations" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Support Activities for Coal Mining" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Support Activities for Metal Mining" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Support Activities for Nonmetallic Minerals (except Fuels) Mining" : "Mining, Quarrying, and Oil and Gas Extraction",
    "Utilities" : "Utilities",
    "Electric Power Generation, Transmission and Distribution" : "Utilities",
    "Hydroelectric Power Generation" : "Utilities",
    "Fossil Fuel Electric Power Generation" : "Utilities",
    "Nuclear Electric Power Generation" : "Utilities",
    "Solar Electric Power Generation" : "Utilities",
    "Wind Electric Power Generation" : "Utilities",
    "Geothermal Electric Power Generation" : "Utilities",
    "Biomass Electric Power Generation" : "Utilities",
    "Other Electric Power Generation" : "Utilities",
    "Electric Bulk Power Transmission and Control" : "Utilities",
    "Electric Power Distribution" : "Utilities",
    "Natural Gas Distribution" : "Utilities",
    "Water, Sewage and Other Systems" : "Utilities",
    "Water Supply and Irrigation Systems" : "Utilities",
    "Sewage Treatment Facilities" : "Utilities",
    "Steam and Air-Conditioning Supply" : "Utilities",
    "Construction" : "Construction",
    "Residential Building Construction" : "Construction",
    "New Single-Family Housing Construction (except For-Sale Builders)" : "Construction",
    "New Multifamily Housing Construction (except For-Sale Builders)" : "Construction",
    "New Housing For-Sale Builders" : "Construction",
    "Residential Remodelers" : "Construction",
    "Nonresidential Building Construction" : "Construction",
    "Industrial Building Construction" : "Construction",
    "Commercial and Institutional Building Construction" : "Construction",
    "Utility System Construction" : "Construction",
    "Water and Sewer Line and Related Structures Construction" : "Construction",
    "Oil and Gas Pipeline and Related Structures Construction" : "Construction",
    "Power and Communication Line and Related Structures Construction" : "Construction",
    "Land Subdivision" : "Construction",
    "Highway, Street, and Bridge Construction" : "Construction",
    "Other Heavy and Civil Engineering Construction" : "Construction",
    "Foundation, Structure, and Building Exterior Contractors" : "Construction",
    "Poured Concrete Foundation and Structure Contractors" : "Construction",
    "Structural Steel and Precast Concrete Contractors" : "Construction",
    "Framing Contractors" : "Construction",
    "Masonry Contractors" : "Construction",
    "Glass and Glazing Contractors" : "Construction",
    "Roofing Contractors" : "Construction",
    "Siding Contractors" : "Construction",
    "Other Foundation, Structure, and Building Exterior Contractors" : "Construction",
    "Building Equipment Contractors" : "Construction",
    "Electrical Contractors and Other Wiring Installation Contractors" : "Construction",
    "Plumbing, Heating, and Air-Conditioning Contractors" : "Construction",
    "Other Building Equipment Contractors" : "Construction",
    "Building Finishing Contractors" : "Construction",
    "Drywall and Insulation Contractors" : "Construction",
    "Painting and Wall Covering Contractors" : "Construction",
    "Flooring Contractors" : "Construction",
    "Tile and Terrazzo Contractors" : "Construction",
    "Finish Carpentry Contractors" : "Construction",
    "Other Building Finishing Contractors" : "Construction",
    "Other Specialty Trade Contractors" : "Construction",
    "Site Preparation Contractors" : "Construction",
    "All Other Specialty Trade Contractors" : "Construction",
    "Manufacturing" : "Manufacturing",
    "Animal Food Manufacturing" : "Manufacturing",
    "Dog and Cat Food Manufacturing" : "Manufacturing",
    "Other Animal Food Manufacturing" : "Manufacturing",
    "Grain and Oilseed Milling" : "Manufacturing",
    "Flour Milling" : "Manufacturing",
    "Rice Milling" : "Manufacturing",
    "Malt Manufacturing" : "Manufacturing",
    "Wet Corn Milling and Starch Manufacturing" : "Manufacturing",
    "Soybean and Other Oilseed Processing" : "Manufacturing",
    "Fats and Oils Refining and Blending" : "Manufacturing",
    "Breakfast Cereal Manufacturing" : "Manufacturing",
    "Sugar and Confectionery Product Manufacturing" : "Manufacturing",
    "Beet Sugar Manufacturing" : "Manufacturing",
    "Cane Sugar Manufacturing" : "Manufacturing",
    "Nonchocolate Confectionery Manufacturing" : "Manufacturing",
    "Chocolate and Confectionery Manufacturing from Cacao Beans" : "Manufacturing",
    "Confectionery Manufacturing from Purchased Chocolate" : "Manufacturing",
    "Fruit and Vegetable Preserving and Specialty Food Manufacturing" : "Manufacturing",
    "Frozen Fruit, Juice, and Vegetable Manufacturing" : "Manufacturing",
    "Frozen Specialty Food Manufacturing" : "Manufacturing",
    "Fruit and Vegetable Canning" : "Manufacturing",
    "Specialty Canning" : "Manufacturing",
    "Dried and Dehydrated Food Manufacturing" : "Manufacturing",
    "Dairy Product Manufacturing" : "Manufacturing",
    "Fluid Milk Manufacturing" : "Manufacturing",
    "Creamery Butter Manufacturing" : "Manufacturing",
    "Cheese Manufacturing" : "Manufacturing",
    "Dry, Condensed, and Evaporated Dairy Product Manufacturing" : "Manufacturing",
    "Ice Cream and Frozen Dessert Manufacturing" : "Manufacturing",
    "Animal Slaughtering and Processing" : "Manufacturing",
    "Animal (except Poultry) Slaughtering" : "Manufacturing",
    "Meat Processed from Carcasses" : "Manufacturing",
    "Rendering and Meat Byproduct Processing" : "Manufacturing",
    "Poultry Processing" : "Manufacturing",
    "Seafood Product Preparation and Packaging" : "Manufacturing",
    "Bakeries and Tortilla Manufacturing" : "Manufacturing",
    "Retail Bakeries" : "Manufacturing",
    "Commercial Bakeries" : "Manufacturing",
    "Frozen Cakes, Pies, and Other Pastries Manufacturing" : "Manufacturing",
    "Cookie and Cracker Manufacturing" : "Manufacturing",
    "Dry Pasta, Dough, and Flour Mixes Manufacturing from Purchased Flour" : "Manufacturing",
    "Tortilla Manufacturing" : "Manufacturing",
    "Other Food Manufacturing" : "Manufacturing",
    "Roasted Nuts and Peanut Butter Manufacturing" : "Manufacturing",
    "Other Snack Food Manufacturing" : "Manufacturing",
    "Coffee and Tea Manufacturing" : "Manufacturing",
    "Flavoring Syrup and Concentrate Manufacturing" : "Manufacturing",
    "Mayonnaise, Dressing, and Other Prepared Sauce Manufacturing" : "Manufacturing",
    "Spice and Extract Manufacturing" : "Manufacturing",
    "Perishable Prepared Food Manufacturing" : "Manufacturing",
    "All Other Miscellaneous Food Manufacturing" : "Manufacturing",
    "Beverage Manufacturing" : "Manufacturing",
    "Soft Drink Manufacturing" : "Manufacturing",
    "Bottled Water Manufacturing" : "Manufacturing",
    "Ice Manufacturing" : "Manufacturing",
    "Breweries" : "Manufacturing",
    "Wineries" : "Manufacturing",
    "Distilleries" : "Manufacturing",
    "Tobacco Manufacturing" : "Manufacturing",
    "Fiber, Yarn, and Thread Mills" : "Manufacturing",
    "Fabric Mills" : "Manufacturing",
    "Broadwoven Fabric Mills" : "Manufacturing",
    "Narrow Fabric Mills and Schiffli Machine Embroidery" : "Manufacturing",
    "Nonwoven Fabric Mills" : "Manufacturing",
    "Knit Fabric Mills" : "Manufacturing",
    "Textile and Fabric Finishing and Fabric Coating Mills" : "Manufacturing",
    "Textile and Fabric Finishing Mills" : "Manufacturing",
    "Fabric Coating Mills" : "Manufacturing",
    "Textile Furnishings Mills" : "Manufacturing",
    "Carpet and Rug Mills" : "Manufacturing",
    "Curtain and Linen Mills" : "Manufacturing",
    "Other Textile Product Mills" : "Manufacturing",
    "Textile Bag and Canvas Mills" : "Manufacturing",
    "Rope, Cordage, Twine, Tire Cord, and Tire Fabric Mills" : "Manufacturing",
    "All Other Miscellaneous Textile Product Mills" : "Manufacturing",
    "Apparel Knitting Mills" : "Manufacturing",
    "Cut and Sew Apparel Manufacturing" : "Manufacturing",
    "Cut and Sew Apparel Contractors" : "Manufacturing",
    "Cut and Sew Apparel Manufacturing (except Contractors)" : "Manufacturing",
    "Apparel Accessories and Other Apparel Manufacturing" : "Manufacturing",
    "Leather and Hide Tanning and Finishing" : "Manufacturing",
    "Footwear Manufacturing" : "Manufacturing",
    "Other Leather and Allied Product Manufacturing" : "Manufacturing",
    "Sawmills and Wood Preservation" : "Manufacturing",
    "Sawmills" : "Manufacturing",
    "Wood Preservation" : "Manufacturing",
    "Veneer, Plywood, and Engineered Wood Product Manufacturing" : "Manufacturing",
    "Hardwood Veneer and Plywood Manufacturing" : "Manufacturing",
    "Softwood Veneer and Plywood Manufacturing" : "Manufacturing",
    "Engineered Wood Member Manufacturing" : "Manufacturing",
    "Reconstituted Wood Product Manufacturing" : "Manufacturing",
    "Other Wood Product Manufacturing" : "Manufacturing",
    "Wood Window and Door Manufacturing" : "Manufacturing",
    "Cut Stock, Resawing Lumber, and Planing" : "Manufacturing",
    "Other Millwork (including Flooring)" : "Manufacturing",
    "Wood Container and Pallet Manufacturing" : "Manufacturing",
    "Manufactured Home (Mobile Home) Manufacturing" : "Manufacturing",
    "Prefabricated Wood Building Manufacturing" : "Manufacturing",
    "All Other Miscellaneous Wood Product Manufacturing" : "Manufacturing",
    "Pulp, Paper, and Paperboard Mills" : "Manufacturing",
    "Pulp Mills" : "Manufacturing",
    "Paper Mills" : "Manufacturing",
    "Paperboard Mills" : "Manufacturing",
    "Converted Paper Product Manufacturing" : "Manufacturing",
    "Corrugated and Solid Fiber Box Manufacturing" : "Manufacturing",
    "Folding Paperboard Box Manufacturing" : "Manufacturing",
    "Other Paperboard Container Manufacturing" : "Manufacturing",
    "Paper Bag and Coated and Treated Paper Manufacturing" : "Manufacturing",
    "Stationery Product Manufacturing" : "Manufacturing",
    "Sanitary Paper Product Manufacturing" : "Manufacturing",
    "All Other Converted Paper Product Manufacturing" : "Manufacturing",
    "Printing and Related Support Activities" : "Manufacturing",
    "Commercial Printing (except Screen and Books)" : "Manufacturing",
    "Commercial Screen Printing" : "Manufacturing",
    "Books Printing" : "Manufacturing",
    "Support Activities for Printing" : "Manufacturing",
    "Petroleum and Coal Products Manufacturing" : "Manufacturing",
    "Petroleum Refineries" : "Manufacturing",
    "Asphalt Paving Mixture and Block Manufacturing" : "Manufacturing",
    "Asphalt Shingle and Coating Materials Manufacturing" : "Manufacturing",
    "Petroleum Lubricating Oil and Grease Manufacturing" : "Manufacturing",
    "All Other Petroleum and Coal Products Manufacturing" : "Manufacturing",
    "Basic Chemical Manufacturing" : "Manufacturing",
    "Petrochemical Manufacturing" : "Manufacturing",
    "Industrial Gas Manufacturing" : "Manufacturing",
    "Synthetic Dye and Pigment Manufacturing" : "Manufacturing",
    "Other Basic Inorganic Chemical Manufacturing" : "Manufacturing",
    "Ethyl Alcohol Manufacturing" : "Manufacturing",
    "Cyclic Crude, Intermediate, and Gum and Wood Chemical Manufacturing" : "Manufacturing",
    "All Other Basic Organic Chemical Manufacturing" : "Manufacturing",
    "Resin, Synthetic Rubber, and Artificial and Synthetic Fibers and Filaments Manufacturing" : "Manufacturing",
    "Plastics Material and Resin Manufacturing" : "Manufacturing",
    "Synthetic Rubber Manufacturing" : "Manufacturing",
    "Artificial and Synthetic Fibers and Filaments Manufacturing" : "Manufacturing",
    "Pesticide, Fertilizer, and Other Agricultural Chemical Manufacturing" : "Manufacturing",
    "Nitrogenous Fertilizer Manufacturing" : "Manufacturing",
    "Phosphatic Fertilizer Manufacturing" : "Manufacturing",
    "Fertilizer (Mixing Only) Manufacturing" : "Manufacturing",
    "Compost Manufacturing" : "Manufacturing",
    "Pesticide and Other Agricultural Chemical Manufacturing" : "Manufacturing",
    "Pharmaceutical and Medicine Manufacturing" : "Manufacturing",
    "Medicinal and Botanical Manufacturing" : "Manufacturing",
    "Pharmaceutical Preparation Manufacturing" : "Manufacturing",
    "In-Vitro Diagnostic Substance Manufacturing" : "Manufacturing",
    "Biological Product (except Diagnostic) Manufacturing" : "Manufacturing",
    "Paint, Coating, and Adhesive Manufacturing" : "Manufacturing",
    "Paint and Coating Manufacturing" : "Manufacturing",
    "Adhesive Manufacturing" : "Manufacturing",
    "Soap, Cleaning Compound, and Toilet Preparation Manufacturing" : "Manufacturing",
    "Soap and Other Detergent Manufacturing" : "Manufacturing",
    "Polish and Other Sanitation Good Manufacturing" : "Manufacturing",
    "Surface Active Agent Manufacturing" : "Manufacturing",
    "Toilet Preparation Manufacturing" : "Manufacturing",
    "Other Chemical Product and Preparation Manufacturing" : "Manufacturing",
    "Printing Ink Manufacturing" : "Manufacturing",
    "Explosives Manufacturing" : "Manufacturing",
    "Custom Compounding of Purchased Resins" : "Manufacturing",
    "Photographic Film, Paper, Plate, Chemical, and Copy Toner Manufacturing" : "Manufacturing",
    "All Other Miscellaneous Chemical Product and Preparation Manufacturing" : "Manufacturing",
    "Plastics Product Manufacturing" : "Manufacturing",
    "Plastics Bag and Pouch Manufacturing" : "Manufacturing",
    "Plastics Packaging Film and Sheet (including Laminated) Manufacturing" : "Manufacturing",
    "Unlaminated Plastics Film and Sheet (except Packaging) Manufacturing" : "Manufacturing",
    "Unlaminated Plastics Profile Shape Manufacturing" : "Manufacturing",
    "Plastics Pipe and Pipe Fitting Manufacturing" : "Manufacturing",
    "Laminated Plastics Plate, Sheet (except Packaging), and Shape Manufacturing" : "Manufacturing",
    "Polystyrene Foam Product Manufacturing" : "Manufacturing",
    "Urethane and Other Foam Product (except Polystyrene) Manufacturing" : "Manufacturing",
    "Plastics Bottle Manufacturing" : "Manufacturing",
    "Plastics Plumbing Fixture Manufacturing" : "Manufacturing",
    "All Other Plastics Product Manufacturing" : "Manufacturing",
    "Rubber Product Manufacturing" : "Manufacturing",
    "Tire Manufacturing (except Retreading)" : "Manufacturing",
    "Tire Retreading" : "Manufacturing",
    "Rubber and Plastics Hoses and Belting Manufacturing" : "Manufacturing",
    "Rubber Product Manufacturing for Mechanical Use" : "Manufacturing",
    "All Other Rubber Product Manufacturing" : "Manufacturing",
    "Clay Product and Refractory Manufacturing" : "Manufacturing",
    "Pottery, Ceramics, and Plumbing Fixture Manufacturing" : "Manufacturing",
    "Clay Building Material and Refractories Manufacturing" : "Manufacturing",
    "Glass and Glass Product Manufacturing" : "Manufacturing",
    "Flat Glass Manufacturing" : "Manufacturing",
    "Other Pressed and Blown Glass and Glassware Manufacturing" : "Manufacturing",
    "Glass Container Manufacturing" : "Manufacturing",
    "Glass Product Manufacturing Made of Purchased Glass" : "Manufacturing",
    "Cement and Concrete Product Manufacturing" : "Manufacturing",
    "Cement Manufacturing" : "Manufacturing",
    "Ready-Mix Concrete Manufacturing" : "Manufacturing",
    "Concrete Block and Brick Manufacturing" : "Manufacturing",
    "Concrete Pipe Manufacturing" : "Manufacturing",
    "Other Concrete Product Manufacturing" : "Manufacturing",
    "Lime and Gypsum Product Manufacturing" : "Manufacturing",
    "Lime Manufacturing" : "Manufacturing",
    "Gypsum Product Manufacturing" : "Manufacturing",
    "Other Nonmetallic Mineral Product Manufacturing" : "Manufacturing",
    "Abrasive Product Manufacturing" : "Manufacturing",
    "Cut Stone and Stone Product Manufacturing" : "Manufacturing",
    "Ground or Treated Mineral and Earth Manufacturing" : "Manufacturing",
    "Mineral Wool Manufacturing" : "Manufacturing",
    "All Other Miscellaneous Nonmetallic Mineral Product Manufacturing" : "Manufacturing",
    "Iron and Steel Mills and Ferroalloy Manufacturing" : "Manufacturing",
    "Steel Product Manufacturing from Purchased Steel" : "Manufacturing",
    "Iron and Steel Pipe and Tube Manufacturing from Purchased Steel" : "Manufacturing",
    "Rolled Steel Shape Manufacturing" : "Manufacturing",
    "Steel Wire Drawing" : "Manufacturing",
    "Alumina and Aluminum Production and Processing" : "Manufacturing",
    "Alumina Refining and Primary Aluminum Production" : "Manufacturing",
    "Secondary Smelting and Alloying of Aluminum" : "Manufacturing",
    "Aluminum Sheet, Plate, and Foil Manufacturing" : "Manufacturing",
    "Other Aluminum Rolling, Drawing, and Extruding" : "Manufacturing",
    "Nonferrous Metal (except Aluminum) Production and Processing" : "Manufacturing",
    "Nonferrous Metal (except Aluminum) Smelting and Refining" : "Manufacturing",
    "Copper Rolling, Drawing, Extruding, and Alloying" : "Manufacturing",
    "Nonferrous Metal (except Copper and Aluminum) Rolling, Drawing, and Extruding" : "Manufacturing",
    "Secondary Smelting, Refining, and Alloying of Nonferrous Metal (except Copper and Aluminum)" : "Manufacturing",
    "Foundries" : "Manufacturing",
    "Iron Foundries" : "Manufacturing",
    "Steel Investment Foundries" : "Manufacturing",
    "Steel Foundries (except Investment)" : "Manufacturing",
    "Nonferrous Metal Die-Casting Foundries" : "Manufacturing",
    "Aluminum Foundries (except Die-Casting)" : "Manufacturing",
    "Other Nonferrous Metal Foundries (except Die-Casting)" : "Manufacturing",
    "Forging and Stamping" : "Manufacturing",
    "Iron and Steel Forging" : "Manufacturing",
    "Nonferrous Forging" : "Manufacturing",
    "Custom Roll Forming" : "Manufacturing",
    "Powder Metallurgy Part Manufacturing" : "Manufacturing",
    "Metal Crown, Closure, and Other Metal Stamping (except Automotive)" : "Manufacturing",
    "Cutlery and Handtool Manufacturing" : "Manufacturing",
    "Metal Kitchen Cookware, Utensil, Cutlery, and Flatware (except Precious) Manufacturing" : "Manufacturing",
    "Saw Blade and Handtool Manufacturing" : "Manufacturing",
    "Architectural and Structural Metals Manufacturing" : "Manufacturing",
    "Prefabricated Metal Building and Component Manufacturing" : "Manufacturing",
    "Fabricated Structural Metal Manufacturing" : "Manufacturing",
    "Plate Work Manufacturing" : "Manufacturing",
    "Metal Window and Door Manufacturing" : "Manufacturing",
    "Sheet Metal Work Manufacturing" : "Manufacturing",
    "Ornamental and Architectural Metal Work Manufacturing" : "Manufacturing",
    "Boiler, Tank, and Shipping Container Manufacturing" : "Manufacturing",
    "Power Boiler and Heat Exchanger Manufacturing" : "Manufacturing",
    "Metal Tank (Heavy Gauge) Manufacturing" : "Manufacturing",
    "Metal Can Manufacturing" : "Manufacturing",
    "Other Metal Container Manufacturing" : "Manufacturing",
    "Hardware Manufacturing" : "Manufacturing",
    "Spring and Wire Product Manufacturing" : "Manufacturing",
    "Spring Manufacturing" : "Manufacturing",
    "Other Fabricated Wire Product Manufacturing" : "Manufacturing",
    "Machine Shops; Turned Product; and Screw, Nut, and Bolt Manufacturing" : "Manufacturing",
    "Machine Shops" : "Manufacturing",
    "Precision Turned Product Manufacturing" : "Manufacturing",
    "Bolt, Nut, Screw, Rivet, and Washer Manufacturing" : "Manufacturing",
    "Coating, Engraving, Heat Treating, and Allied Activities" : "Manufacturing",
    "Metal Heat Treating" : "Manufacturing",
    "Metal Coating, Engraving (except Jewelry and Silverware), and Allied Services to Manufacturers" : "Manufacturing",
    "Electroplating, Plating, Polishing, Anodizing, and Coloring" : "Manufacturing",
    "Other Fabricated Metal Product Manufacturing" : "Manufacturing",
    "Industrial Valve Manufacturing" : "Manufacturing",
    "Fluid Power Valve and Hose Fitting Manufacturing" : "Manufacturing",
    "Plumbing Fixture Fitting and Trim Manufacturing" : "Manufacturing",
    "Other Metal Valve and Pipe Fitting Manufacturing" : "Manufacturing",
    "Ball and Roller Bearing Manufacturing" : "Manufacturing",
    "Small Arms Ammunition Manufacturing" : "Manufacturing",
    "Ammunition (except Small Arms) Manufacturing" : "Manufacturing",
    "Small Arms, Ordnance, and Ordnance Accessories Manufacturing" : "Manufacturing",
    "Fabricated Pipe and Pipe Fitting Manufacturing" : "Manufacturing",
    "All Other Miscellaneous Fabricated Metal Product Manufacturing" : "Manufacturing",
    "Agriculture, Construction, and Mining Machinery Manufacturing" : "Manufacturing",
    "Farm Machinery and Equipment Manufacturing" : "Manufacturing",
    "Lawn and Garden Tractor and Home Lawn and Garden Equipment Manufacturing" : "Manufacturing",
    "Construction Machinery Manufacturing" : "Manufacturing",
    "Mining Machinery and Equipment Manufacturing" : "Manufacturing",
    "Oil and Gas Field Machinery and Equipment Manufacturing" : "Manufacturing",
    "Industrial Machinery Manufacturing" : "Manufacturing",
    "Food Product Machinery Manufacturing" : "Manufacturing",
    "Semiconductor Machinery Manufacturing" : "Manufacturing",
    "Sawmill, Woodworking, and Paper Machinery Manufacturing" : "Manufacturing",
    "All Other Industrial Machinery Manufacturing" : "Manufacturing",
    "Commercial and Service Industry Machinery Manufacturing" : "Manufacturing",
    "Ventilation, Heating, Air-Conditioning, and Commercial Refrigeration Equipment Manufacturing" : "Manufacturing",
    "Industrial and Commercial Fan and Blower and Air Purification Equipment Manufacturing" : "Manufacturing",
    "Heating Equipment (except Warm Air Furnaces) Manufacturing" : "Manufacturing",
    "Air-Conditioning and Warm Air Heating Equipment and Commercial and Industrial Refrigeration Equipment Manufacturing" : "Manufacturing",
    "Metalworking Machinery Manufacturing" : "Manufacturing",
    "Industrial Mold Manufacturing" : "Manufacturing",
    "Special Die and Tool, Die Set, Jig, and Fixture Manufacturing" : "Manufacturing",
    "Cutting Tool and Machine Tool Accessory Manufacturing" : "Manufacturing",
    "Machine Tool Manufacturing" : "Manufacturing",
    "Rolling Mill and Other Metalworking Machinery Manufacturing" : "Manufacturing",
    "Engine, Turbine, and Power Transmission Equipment Manufacturing" : "Manufacturing",
    "Turbine and Turbine Generator Set Units Manufacturing" : "Manufacturing",
    "Speed Changer, Industrial High-Speed Drive, and Gear Manufacturing" : "Manufacturing",
    "Mechanical Power Transmission Equipment Manufacturing" : "Manufacturing",
    "Other Engine Equipment Manufacturing" : "Manufacturing",
    "Other General Purpose Machinery Manufacturing" : "Manufacturing",
    "Air and Gas Compressor Manufacturing" : "Manufacturing",
    "Measuring, Dispensing, and Other Pumping Equipment Manufacturing" : "Manufacturing",
    "Elevator and Moving Stairway Manufacturing" : "Manufacturing",
    "Conveyor and Conveying Equipment Manufacturing" : "Manufacturing",
    "Overhead Traveling Crane, Hoist, and Monorail System Manufacturing" : "Manufacturing",
    "Industrial Truck, Tractor, Trailer, and Stacker Machinery Manufacturing" : "Manufacturing",
    "Power-Driven Handtool Manufacturing" : "Manufacturing",
    "Welding and Soldering Equipment Manufacturing" : "Manufacturing",
    "Packaging Machinery Manufacturing" : "Manufacturing",
    "Industrial Process Furnace and Oven Manufacturing" : "Manufacturing",
    "Fluid Power Cylinder and Actuator Manufacturing" : "Manufacturing",
    "Fluid Power Pump and Motor Manufacturing" : "Manufacturing",
    "All Other Miscellaneous General Purpose Machinery Manufacturing" : "Manufacturing",
    "Computer and Peripheral Equipment Manufacturing" : "Manufacturing",
    "Electronic Computer Manufacturing" : "Manufacturing",
    "Computer Storage Device Manufacturing" : "Manufacturing",
    "Computer Terminal and Other Computer Peripheral Equipment Manufacturing" : "Manufacturing",
    "Communications Equipment Manufacturing" : "Manufacturing",
    "Telephone Apparatus Manufacturing" : "Manufacturing",
    "Radio and Television Broadcasting and Wireless Communications Equipment Manufacturing" : "Manufacturing",
    "Other Communications Equipment Manufacturing" : "Manufacturing",
    "Audio and Video Equipment Manufacturing" : "Manufacturing",
    "Semiconductor and Other Electronic Component Manufacturing" : "Manufacturing",
    "Bare Printed Circuit Board Manufacturing" : "Manufacturing",
    "Semiconductor and Related Device Manufacturing" : "Manufacturing",
    "Capacitor, Resistor, Coil, Transformer, and Other Inductor Manufacturing" : "Manufacturing",
    "Electronic Connector Manufacturing" : "Manufacturing",
    "Printed Circuit Assembly (Electronic Assembly) Manufacturing" : "Manufacturing",
    "Other Electronic Component Manufacturing" : "Manufacturing",
    "Navigational, Measuring, Electromedical, and Control Instruments Manufacturing" : "Manufacturing",
    "Electromedical and Electrotherapeutic Apparatus Manufacturing" : "Manufacturing",
    "Search, Detection, Navigation, Guidance, Aeronautical, and Nautical System and Instrument Manufacturing" : "Manufacturing",
    "Automatic Environmental Control Manufacturing for Residential, Commercial, and Appliance Use" : "Manufacturing",
    "Instruments and Related Products Manufacturing for Measuring, Displaying, and Controlling Industrial Process Variables" : "Manufacturing",
    "Totalizing Fluid Meter and Counting Device Manufacturing" : "Manufacturing",
    "Instrument Manufacturing for Measuring and Testing Electricity and Electrical Signals" : "Manufacturing",
    "Analytical Laboratory Instrument Manufacturing" : "Manufacturing",
    "Irradiation Apparatus Manufacturing" : "Manufacturing",
    "Other Measuring and Controlling Device Manufacturing" : "Manufacturing",
    "Manufacturing and Reproducing Magnetic and Optical Media" : "Manufacturing",
    "Electric Lighting Equipment Manufacturing" : "Manufacturing",
    "Residential Electric Lighting Fixture Manufacturing" : "Manufacturing",
    "Commercial, Industrial, and Institutional Electric Lighting Fixture Manufacturing" : "Manufacturing",
    "Electric Lamp Bulb and Other Lighting Equipment Manufacturing" : "Manufacturing",
    "Household Appliance Manufacturing" : "Manufacturing",
    "Small Electrical Appliance Manufacturing" : "Manufacturing",
    "Major Household Appliance Manufacturing" : "Manufacturing",
    "Electrical Equipment Manufacturing" : "Manufacturing",
    "Power, Distribution, and Specialty Transformer Manufacturing" : "Manufacturing",
    "Motor and Generator Manufacturing" : "Manufacturing",
    "Switchgear and Switchboard Apparatus Manufacturing" : "Manufacturing",
    "Relay and Industrial Control Manufacturing" : "Manufacturing",
    "Other Electrical Equipment and Component Manufacturing" : "Manufacturing",
    "Battery Manufacturing" : "Manufacturing",
    "Fiber Optic Cable Manufacturing" : "Manufacturing",
    "Other Communication and Energy Wire Manufacturing" : "Manufacturing",
    "Current-Carrying Wiring Device Manufacturing" : "Manufacturing",
    "Noncurrent-Carrying Wiring Device Manufacturing" : "Manufacturing",
    "Carbon and Graphite Product Manufacturing" : "Manufacturing",
    "All Other Miscellaneous Electrical Equipment and Component Manufacturing" : "Manufacturing",
    "Motor Vehicle Manufacturing" : "Manufacturing",
    "Automobile and Light Duty Motor Vehicle Manufacturing" : "Manufacturing",
    "Heavy Duty Truck Manufacturing" : "Manufacturing",
    "Motor Vehicle Body and Trailer Manufacturing" : "Manufacturing",
    "Motor Vehicle Body Manufacturing" : "Manufacturing",
    "Truck Trailer Manufacturing" : "Manufacturing",
    "Motor Home Manufacturing" : "Manufacturing",
    "Travel Trailer and Camper Manufacturing" : "Manufacturing",
    "Motor Vehicle Parts Manufacturing" : "Manufacturing",
    "Motor Vehicle Gasoline Engine and Engine Parts Manufacturing" : "Manufacturing",
    "Motor Vehicle Electrical and Electronic Equipment Manufacturing" : "Manufacturing",
    "Motor Vehicle Steering and Suspension Components (except Spring) Manufacturing" : "Manufacturing",
    "Motor Vehicle Brake System Manufacturing" : "Manufacturing",
    "Motor Vehicle Transmission and Power Train Parts Manufacturing" : "Manufacturing",
    "Motor Vehicle Seating and Interior Trim Manufacturing" : "Manufacturing",
    "Motor Vehicle Metal Stamping" : "Manufacturing",
    "Other Motor Vehicle Parts Manufacturing" : "Manufacturing",
    "Aerospace Product and Parts Manufacturing" : "Manufacturing",
    "Aircraft Manufacturing" : "Manufacturing",
    "Aircraft Engine and Engine Parts Manufacturing" : "Manufacturing",
    "Other Aircraft Parts and Auxiliary Equipment Manufacturing" : "Manufacturing",
    "Guided Missile and Space Vehicle Manufacturing" : "Manufacturing",
    "Guided Missile and Space Vehicle Propulsion Unit and Propulsion Unit Parts Manufacturing" : "Manufacturing",
    "Other Guided Missile and Space Vehicle Parts and Auxiliary Equipment Manufacturing" : "Manufacturing",
    "Railroad Rolling Stock Manufacturing" : "Manufacturing",
    "Ship and Boat Building" : "Manufacturing",
    "Ship Building and Repairing" : "Manufacturing",
    "Boat Building" : "Manufacturing",
    "Other Transportation Equipment Manufacturing" : "Manufacturing",
    "Motorcycle, Bicycle, and Parts Manufacturing" : "Manufacturing",
    "Military Armored Vehicle, Tank, and Tank Component Manufacturing" : "Manufacturing",
    "All Other Transportation Equipment Manufacturing" : "Manufacturing",
    "Household and Institutional Furniture and Kitchen Cabinet Manufacturing" : "Manufacturing",
    "Wood Kitchen Cabinet and Countertop Manufacturing" : "Manufacturing",
    "Upholstered Household Furniture Manufacturing" : "Manufacturing",
    "Nonupholstered Wood Household Furniture Manufacturing" : "Manufacturing",
    "Household Furniture (except Wood and Upholstered) Manufacturing" : "Manufacturing",
    "Institutional Furniture Manufacturing" : "Manufacturing",
    "Office Furniture (including Fixtures) Manufacturing" : "Manufacturing",
    "Wood Office Furniture Manufacturing" : "Manufacturing",
    "Custom Architectural Woodwork and Millwork Manufacturing" : "Manufacturing",
    "Office Furniture (except Wood) Manufacturing" : "Manufacturing",
    "Showcase, Partition, Shelving, and Locker Manufacturing" : "Manufacturing",
    "Other Furniture Related Product Manufacturing" : "Manufacturing",
    "Mattress Manufacturing" : "Manufacturing",
    "Blind and Shade Manufacturing" : "Manufacturing",
    "Medical Equipment and Supplies Manufacturing" : "Manufacturing",
    "Surgical and Medical Instrument Manufacturing" : "Manufacturing",
    "Surgical Appliance and Supplies Manufacturing" : "Manufacturing",
    "Dental Equipment and Supplies Manufacturing" : "Manufacturing",
    "Ophthalmic Goods Manufacturing" : "Manufacturing",
    "Dental Laboratories" : "Manufacturing",
    "Other Miscellaneous Manufacturing" : "Manufacturing",
    "Jewelry and Silverware Manufacturing" : "Manufacturing",
    "Sporting and Athletic Goods Manufacturing" : "Manufacturing",
    "Doll, Toy, and Game Manufacturing" : "Manufacturing",
    "Office Supplies (except Paper) Manufacturing" : "Manufacturing",
    "Sign Manufacturing" : "Manufacturing",
    "Gasket, Packing, and Sealing Device Manufacturing" : "Manufacturing",
    "Musical Instrument Manufacturing" : "Manufacturing",
    "Fastener, Button, Needle, and Pin Manufacturing" : "Manufacturing",
    "Broom, Brush, and Mop Manufacturing" : "Manufacturing",
    "Burial Casket Manufacturing" : "Manufacturing",
    "All Other Miscellaneous Manufacturing" : "Manufacturing",
    "Wholesale Trade" : "Wholesale Trade",
    "Motor Vehicle and Motor Vehicle Parts and Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Automobile and Other Motor Vehicle Merchant Wholesalers" : "Wholesale Trade",
    "Motor Vehicle Supplies and New Parts Merchant Wholesalers" : "Wholesale Trade",
    "Tire and Tube Merchant Wholesalers" : "Wholesale Trade",
    "Motor Vehicle Parts (Used) Merchant Wholesalers" : "Wholesale Trade",
    "Furniture and Home Furnishing Merchant Wholesalers" : "Wholesale Trade",
    "Furniture Merchant Wholesalers" : "Wholesale Trade",
    "Home Furnishing Merchant Wholesalers" : "Wholesale Trade",
    "Lumber and Other Construction Materials Merchant Wholesalers" : "Wholesale Trade",
    "Lumber, Plywood, Millwork, and Wood Panel Merchant Wholesalers" : "Wholesale Trade",
    "Brick, Stone, and Related Construction Material Merchant Wholesalers" : "Wholesale Trade",
    "Roofing, Siding, and Insulation Material Merchant Wholesalers" : "Wholesale Trade",
    "Other Construction Material Merchant Wholesalers" : "Wholesale Trade",
    "Professional and Commercial Equipment and Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Photographic Equipment and Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Office Equipment Merchant Wholesalers" : "Wholesale Trade",
    "Computer and Computer Peripheral Equipment and Software Merchant Wholesalers" : "Wholesale Trade",
    "Other Commercial Equipment Merchant Wholesalers" : "Wholesale Trade",
    "Medical, Dental, and Hospital Equipment and Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Ophthalmic Goods Merchant Wholesalers" : "Wholesale Trade",
    "Other Professional Equipment and Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Metal and Mineral (except Petroleum) Merchant Wholesalers" : "Wholesale Trade",
    "Metal Service Centers and Other Metal Merchant Wholesalers" : "Wholesale Trade",
    "Coal and Other Mineral and Ore Merchant Wholesalers" : "Wholesale Trade",
    "Household Appliances and Electrical and Electronic Goods Merchant Wholesalers" : "Wholesale Trade",
    "Electrical Apparatus and Equipment, Wiring Supplies, and Related Equipment Merchant Wholesalers" : "Wholesale Trade",
    "Household Appliances, Electric Housewares, and Consumer Electronics Merchant Wholesalers" : "Wholesale Trade",
    "Other Electronic Parts and Equipment Merchant Wholesalers" : "Wholesale Trade",
    "Hardware, and Plumbing and Heating Equipment and Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Hardware Merchant Wholesalers" : "Wholesale Trade",
    "Plumbing and Heating Equipment and Supplies (Hydronics) Merchant Wholesalers" : "Wholesale Trade",
    "Warm Air Heating and Air-Conditioning Equipment and Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Refrigeration Equipment and Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Machinery, Equipment, and Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Construction and Mining (except Oil Well) Machinery and Equipment Merchant Wholesalers" : "Wholesale Trade",
    "Farm and Garden Machinery and Equipment Merchant Wholesalers" : "Wholesale Trade",
    "Industrial Machinery and Equipment Merchant Wholesalers" : "Wholesale Trade",
    "Industrial Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Service Establishment Equipment and Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Transportation Equipment and Supplies (except Motor Vehicle) Merchant Wholesalers" : "Wholesale Trade",
    "Miscellaneous Durable Goods Merchant Wholesalers" : "Wholesale Trade",
    "Sporting and Recreational Goods and Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Toy and Hobby Goods and Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Recyclable Material Merchant Wholesalers" : "Wholesale Trade",
    "Jewelry, Watch, Precious Stone, and Precious Metal Merchant Wholesalers" : "Wholesale Trade",
    "Other Miscellaneous Durable Goods Merchant Wholesalers" : "Wholesale Trade",
    "Paper and Paper Product Merchant Wholesalers" : "Wholesale Trade",
    "Printing and Writing Paper Merchant Wholesalers" : "Wholesale Trade",
    "Stationery and Office Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Industrial and Personal Service Paper Merchant Wholesalers" : "Wholesale Trade",
    "Drugs and Druggists' Sundries Merchant Wholesalers" : "Wholesale Trade",
    "Apparel, Piece Goods, and Notions Merchant Wholesalers" : "Wholesale Trade",
    "Piece Goods, Notions, and Other Dry Goods Merchant Wholesalers" : "Wholesale Trade",
    "Footwear Merchant Wholesalers" : "Wholesale Trade",
    "Clothing and Clothing Accessories Merchant Wholesalers" : "Wholesale Trade",
    "Grocery and Related Product Merchant Wholesalers" : "Wholesale Trade",
    "General Line Grocery Merchant Wholesalers" : "Wholesale Trade",
    "Packaged Frozen Food Merchant Wholesalers" : "Wholesale Trade",
    "Dairy Product (except Dried or Canned) Merchant Wholesalers" : "Wholesale Trade",
    "Poultry and Poultry Product Merchant Wholesalers" : "Wholesale Trade",
    "Confectionery Merchant Wholesalers" : "Wholesale Trade",
    "Fish and Seafood Merchant Wholesalers" : "Wholesale Trade",
    "Meat and Meat Product Merchant Wholesalers" : "Wholesale Trade",
    "Fresh Fruit and Vegetable Merchant Wholesalers" : "Wholesale Trade",
    "Other Grocery and Related Products Merchant Wholesalers" : "Wholesale Trade",
    "Farm Product Raw Material Merchant Wholesalers" : "Wholesale Trade",
    "Grain and Field Bean Merchant Wholesalers" : "Wholesale Trade",
    "Livestock Merchant Wholesalers" : "Wholesale Trade",
    "Other Farm Product Raw Material Merchant Wholesalers" : "Wholesale Trade",
    "Chemical and Allied Products Merchant Wholesalers" : "Wholesale Trade",
    "Plastics Materials and Basic Forms and Shapes Merchant Wholesalers" : "Wholesale Trade",
    "Other Chemical and Allied Products Merchant Wholesalers" : "Wholesale Trade",
    "Petroleum and Petroleum Products Merchant Wholesalers" : "Wholesale Trade",
    "Petroleum Bulk Stations and Terminals" : "Wholesale Trade",
    "Petroleum and Petroleum Products Merchant Wholesalers (except Bulk Stations and Terminals)" : "Wholesale Trade",
    "Beer, Wine, and Distilled Alcoholic Beverage Merchant Wholesalers" : "Wholesale Trade",
    "Beer and Ale Merchant Wholesalers" : "Wholesale Trade",
    "Wine and Distilled Alcoholic Beverage Merchant Wholesalers" : "Wholesale Trade",
    "Miscellaneous Nondurable Goods Merchant Wholesalers" : "Wholesale Trade",
    "Farm Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Book, Periodical, and Newspaper Merchant Wholesalers" : "Wholesale Trade",
    "Flower, Nursery Stock, and Florists' Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Tobacco Product and Electronic Cigarette Merchant Wholesalers" : "Wholesale Trade",
    "Paint, Varnish, and Supplies Merchant Wholesalers" : "Wholesale Trade",
    "Other Miscellaneous Nondurable Goods Merchant Wholesalers" : "Wholesale Trade",
    "Wholesale Trade Agents and Brokers" : "Wholesale Trade",
    "Retail Trade" : "Retail Trade",
    "Automobile Dealers" : "Retail Trade",
    "New Car Dealers" : "Retail Trade",
    "Used Car Dealers" : "Retail Trade",
    "Other Motor Vehicle Dealers" : "Retail Trade",
    "Recreational Vehicle Dealers" : "Retail Trade",
    "Boat Dealers" : "Retail Trade",
    "Motorcycle, ATV, and All Other Motor Vehicle Dealers" : "Retail Trade",
    "Automotive Parts, Accessories, and Tire Retailers" : "Retail Trade",
    "Automotive Parts and Accessories Retailers" : "Retail Trade",
    "Tire Dealers" : "Retail Trade",
    "Building Material and Supplies Dealers" : "Retail Trade",
    "Home Centers" : "Retail Trade",
    "Paint and Wallpaper Retailers" : "Retail Trade",
    "Hardware Retailers" : "Retail Trade",
    "Other Building Material Dealers" : "Retail Trade",
    "Lawn and Garden Equipment and Supplies Retailers" : "Retail Trade",
    "Outdoor Power Equipment Retailers" : "Retail Trade",
    "Nursery, Garden Center, and Farm Supply Retailers" : "Retail Trade",
    "Grocery and Convenience Retailers" : "Retail Trade",
    "Supermarkets and Other Grocery Retailers (except Convenience Retailers)" : "Retail Trade",
    "Convenience Retailers" : "Retail Trade",
    "Vending Machine Operators" : "Retail Trade",
    "Specialty Food Retailers" : "Retail Trade",
    "Fruit and Vegetable Retailers" : "Retail Trade",
    "Meat Retailers" : "Retail Trade",
    "Fish and Seafood Retailers" : "Retail Trade",
    "Baked Goods Retailers" : "Retail Trade",
    "Confectionery and Nut Retailers" : "Retail Trade",
    "All Other Specialty Food Retailers" : "Retail Trade",
    "Beer, Wine, and Liquor Retailers" : "Retail Trade",
    "Furniture and Home Furnishings Retailers" : "Retail Trade",
    "Furniture Retailers" : "Retail Trade",
    "Floor Covering Retailers" : "Retail Trade",
    "Window Treatment Retailers" : "Retail Trade",
    "All Other Home Furnishings Retailers" : "Retail Trade",
    "Electronics and Appliance Retailers" : "Retail Trade",
    "Department Stores" : "Retail Trade",
    "Warehouse Clubs, Supercenters, and Other General Merchandise Retailers" : "Retail Trade",
    "Warehouse Clubs and Supercenters" : "Retail Trade",
    "All Other General Merchandise Retailers" : "Retail Trade",
    "Health and Personal Care Retailers" : "Retail Trade",
    "Pharmacies and Drug Retailers" : "Retail Trade",
    "Cosmetics, Beauty Supplies, and Perfume Retailers" : "Retail Trade",
    "Optical Goods Retailers" : "Retail Trade",
    "Food (Health) Supplement Retailers" : "Retail Trade",
    "All Other Health and Personal Care Retailers" : "Retail Trade",
    "Gasoline Stations" : "Retail Trade",
    "Gasoline Stations with Convenience Stores" : "Retail Trade",
    "Other Gasoline Stations" : "Retail Trade",
    "Fuel Dealers" : "Retail Trade",
    "Clothing and Clothing Accessories Retailers" : "Retail Trade",
    "Shoe Retailers" : "Retail Trade",
    "Jewelry, Luggage, and Leather Goods Retailers" : "Retail Trade",
    "Jewelry Retailers" : "Retail Trade",
    "Luggage and Leather Goods Retailers" : "Retail Trade",
    "Sporting Goods, Hobby, and Musical Instrument Retailers" : "Retail Trade",
    "Sporting Goods Retailers" : "Retail Trade",
    "Hobby, Toy, and Game Retailers" : "Retail Trade",
    "Sewing, Needlework, and Piece Goods Retailers" : "Retail Trade",
    "Musical Instrument and Supplies Retailers" : "Retail Trade",
    "Book Retailers and News Dealers" : "Retail Trade",
    "Florists" : "Retail Trade",
    "Office Supplies, Stationery, and Gift Retailers" : "Retail Trade",
    "Office Supplies and Stationery Retailers" : "Retail Trade",
    "Gift, Novelty, and Souvenir Retailers" : "Retail Trade",
    "Used Merchandise Retailers" : "Retail Trade",
    "Other Miscellaneous Retailers" : "Retail Trade",
    "Pet and Pet Supplies Retailers" : "Retail Trade",
    "Art Dealers" : "Retail Trade",
    "Manufactured (Mobile) Home Dealers" : "Retail Trade",
    "Tobacco, Electronic Cigarette, and Other Smoking Supplies Retailers" : "Retail Trade",
    "All Other Miscellaneous Retailers" : "Retail Trade",
    "Transportation and Warehousing" : "Transportation and Warehousing",
    "Scheduled Air Transportation" : "Transportation and Warehousing",
    "Scheduled Passenger Air Transportation" : "Transportation and Warehousing",
    "Scheduled Freight Air Transportation" : "Transportation and Warehousing",
    "Nonscheduled Air Transportation" : "Transportation and Warehousing",
    "Nonscheduled Chartered Passenger Air Transportation" : "Transportation and Warehousing",
    "Nonscheduled Chartered Freight Air Transportation" : "Transportation and Warehousing",
    "Other Nonscheduled Air Transportation" : "Transportation and Warehousing",
    "Rail Transportation" : "Transportation and Warehousing",
    "Line-Haul Railroads" : "Transportation and Warehousing",
    "Short Line Railroads" : "Transportation and Warehousing",
    "Deep Sea, Coastal, and Great Lakes Water Transportation" : "Transportation and Warehousing",
    "Deep Sea Freight Transportation" : "Transportation and Warehousing",
    "Deep Sea Passenger Transportation" : "Transportation and Warehousing",
    "Coastal and Great Lakes Freight Transportation" : "Transportation and Warehousing",
    "Coastal and Great Lakes Passenger Transportation" : "Transportation and Warehousing",
    "Inland Water Transportation" : "Transportation and Warehousing",
    "Inland Water Freight Transportation" : "Transportation and Warehousing",
    "Inland Water Passenger Transportation" : "Transportation and Warehousing",
    "General Freight Trucking" : "Transportation and Warehousing",
    "General Freight Trucking, Local" : "Transportation and Warehousing",
    "General Freight Trucking, Long-Distance, Truckload" : "Transportation and Warehousing",
    "General Freight Trucking, Long-Distance, Less Than Truckload" : "Transportation and Warehousing",
    "Specialized Freight Trucking" : "Transportation and Warehousing",
    "Used Household and Office Goods Moving" : "Transportation and Warehousing",
    "Specialized Freight (except Used Goods) Trucking, Local" : "Transportation and Warehousing",
    "Specialized Freight (except Used Goods) Trucking, Long-Distance" : "Transportation and Warehousing",
    "Urban Transit Systems" : "Transportation and Warehousing",
    "Mixed Mode Transit Systems" : "Transportation and Warehousing",
    "Commuter Rail Systems" : "Transportation and Warehousing",
    "Bus and Other Motor Vehicle Transit Systems" : "Transportation and Warehousing",
    "Other Urban Transit Systems" : "Transportation and Warehousing",
    "Interurban and Rural Bus Transportation" : "Transportation and Warehousing",
    "Taxi and Limousine Service" : "Transportation and Warehousing",
    "Taxi and Ridesharing Services" : "Transportation and Warehousing",
    "Limousine Service" : "Transportation and Warehousing",
    "School and Employee Bus Transportation" : "Transportation and Warehousing",
    "Charter Bus Industry" : "Transportation and Warehousing",
    "Other Transit and Ground Passenger Transportation" : "Transportation and Warehousing",
    "Special Needs Transportation" : "Transportation and Warehousing",
    "All Other Transit and Ground Passenger Transportation" : "Transportation and Warehousing",
    "Pipeline Transportation of Crude Oil" : "Transportation and Warehousing",
    "Pipeline Transportation of Natural Gas" : "Transportation and Warehousing",
    "Other Pipeline Transportation" : "Transportation and Warehousing",
    "Pipeline Transportation of Refined Petroleum Products" : "Transportation and Warehousing",
    "All Other Pipeline Transportation" : "Transportation and Warehousing",
    "Scenic and Sightseeing Transportation, Land" : "Transportation and Warehousing",
    "Scenic and Sightseeing Transportation, Water" : "Transportation and Warehousing",
    "Scenic and Sightseeing Transportation, Other" : "Transportation and Warehousing",
    "Support Activities for Air Transportation" : "Transportation and Warehousing",
    "Air Traffic Control" : "Transportation and Warehousing",
    "Other Airport Operations" : "Transportation and Warehousing",
    "Other Support Activities for Air Transportation" : "Transportation and Warehousing",
    "Support Activities for Rail Transportation" : "Transportation and Warehousing",
    "Support Activities for Water Transportation" : "Transportation and Warehousing",
    "Port and Harbor Operations" : "Transportation and Warehousing",
    "Marine Cargo Handling" : "Transportation and Warehousing",
    "Navigational Services to Shipping" : "Transportation and Warehousing",
    "Other Support Activities for Water Transportation" : "Transportation and Warehousing",
    "Support Activities for Road Transportation" : "Transportation and Warehousing",
    "Motor Vehicle Towing" : "Transportation and Warehousing",
    "Other Support Activities for Road Transportation" : "Transportation and Warehousing",
    "Freight Transportation Arrangement" : "Transportation and Warehousing",
    "Other Support Activities for Transportation" : "Transportation and Warehousing",
    "Packing and Crating" : "Transportation and Warehousing",
    "All Other Support Activities for Transportation" : "Transportation and Warehousing",
    "Postal Service" : "Transportation and Warehousing",
    "Couriers and Express Delivery Services" : "Transportation and Warehousing",
    "Local Messengers and Local Delivery" : "Transportation and Warehousing",
    "Warehousing and Storage" : "Transportation and Warehousing",
    "General Warehousing and Storage" : "Transportation and Warehousing",
    "Refrigerated Warehousing and Storage" : "Transportation and Warehousing",
    "Farm Product Warehousing and Storage" : "Transportation and Warehousing",
    "Other Warehousing and Storage" : "Transportation and Warehousing",
    "Information" : "Information",
    "Motion Picture and Video Industries" : "Information",
    "Motion Picture and Video Production" : "Information",
    "Motion Picture and Video Distribution" : "Information",
    "Motion Picture Theaters (except Drive-Ins)" : "Information",
    "Drive-In Motion Picture Theaters" : "Information",
    "Teleproduction and Other Postproduction Services" : "Information",
    "Other Motion Picture and Video Industries" : "Information",
    "Sound Recording Industries" : "Information",
    "Music Publishers" : "Information",
    "Sound Recording Studios" : "Information",
    "Record Production and Distribution" : "Information",
    "Other Sound Recording Industries" : "Information",
    "Newspaper, Periodical, Book, and Directory Publishers" : "Information",
    "Newspaper Publishers" : "Information",
    "Periodical Publishers" : "Information",
    "Book Publishers" : "Information",
    "Directory and Mailing List Publishers" : "Information",
    "Greeting Card Publishers" : "Information",
    "All Other Publishers" : "Information",
    "Software Publishers" : "Information",
    "Radio and Television Broadcasting Stations" : "Information",
    "Radio Broadcasting Stations" : "Information",
    "Television Broadcasting Stations" : "Information",
    "Media Streaming Distribution Services, Social Networks, and Other Media Networks and Content Providers" : "Information",
    "Wired and Wireless Telecommunications (except Satellite)" : "Information",
    "Wired Telecommunications Carriers" : "Information",
    "Wireless Telecommunications Carriers (except Satellite)" : "Information",
    "Telecommunications Resellers" : "Information",
    "Agents for Wireless Telecommunications Services" : "Information",
    "Satellite Telecommunications" : "Information",
    "All Other Telecommunications" : "Information",
    "Computing Infrastructure Providers, Data Processing, Web Hosting, and Related Services" : "Information",
    "Web Search Portals, Libraries, Archives, and Other Information Services" : "Information",
    "Libraries and Archives" : "Information",
    "Web Search Portals and All Other Information Services" : "Information",
    "Finance and Insurance" : "Finance and Insurance",
    "Monetary Authorities-Central Bank" : "Finance and Insurance",
    "Depository Credit Intermediation" : "Finance and Insurance",
    "Commercial Banking" : "Finance and Insurance",
    "Credit Unions" : "Finance and Insurance",
    "Savings Institutions and Other Depository Credit Intermediation" : "Finance and Insurance",
    "Nondepository Credit Intermediation" : "Finance and Insurance",
    "Credit Card Issuing" : "Finance and Insurance",
    "Sales Financing" : "Finance and Insurance",
    "Consumer Lending" : "Finance and Insurance",
    "Real Estate Credit" : "Finance and Insurance",
    "International, Secondary Market, and All Other Nondepository Credit Intermediation" : "Finance and Insurance",
    "Activities Related to Credit Intermediation" : "Finance and Insurance",
    "Mortgage and Nonmortgage Loan Brokers" : "Finance and Insurance",
    "Financial Transactions Processing, Reserve, and Clearinghouse Activities" : "Finance and Insurance",
    "Other Activities Related to Credit Intermediation" : "Finance and Insurance",
    "Securities and Commodity Contracts Intermediation and Brokerage" : "Finance and Insurance",
    "Investment Banking and Securities Intermediation" : "Finance and Insurance",
    "Commodity Contracts Intermediation" : "Finance and Insurance",
    "Securities and Commodity Exchanges" : "Finance and Insurance",
    "Other Financial Investment Activities" : "Finance and Insurance",
    "Miscellaneous Intermediation" : "Finance and Insurance",
    "Portfolio Management and Investment Advice" : "Finance and Insurance",
    "Trust, Fiduciary, and Custody Activities" : "Finance and Insurance",
    "Miscellaneous Financial Investment Activities" : "Finance and Insurance",
    "Insurance Carriers" : "Finance and Insurance",
    "Direct Life Insurance Carriers" : "Finance and Insurance",
    "Direct Health and Medical Insurance Carriers" : "Finance and Insurance",
    "Direct Property and Casualty Insurance Carriers" : "Finance and Insurance",
    "Direct Title Insurance Carriers" : "Finance and Insurance",
    "Other Direct Insurance (except Life, Health, and Medical) Carriers" : "Finance and Insurance",
    "Reinsurance Carriers" : "Finance and Insurance",
    "Agencies, Brokerages, and Other Insurance Related Activities" : "Finance and Insurance",
    "Insurance Agencies and Brokerages" : "Finance and Insurance",
    "Claims Adjusting" : "Finance and Insurance",
    "Pharmacy Benefit Management and Other Third Party Administration of Insurance and Pension Funds" : "Finance and Insurance",
    "All Other Insurance Related Activities" : "Finance and Insurance",
    "Insurance and Employee Benefit Funds" : "Finance and Insurance",
    "Pension Funds" : "Finance and Insurance",
    "Health and Welfare Funds" : "Finance and Insurance",
    "Other Insurance Funds" : "Finance and Insurance",
    "Other Investment Pools and Funds" : "Finance and Insurance",
    "Open-End Investment Funds" : "Finance and Insurance",
    "Trusts, Estates, and Agency Accounts" : "Finance and Insurance",
    "Other Financial Vehicles" : "Finance and Insurance",
    "Real Estate and Rental and Leasing" : "Real Estate and Rental and Leasing",
    "Lessors of Real Estate" : "Real Estate and Rental and Leasing",
    "Lessors of Residential Buildings and Dwellings" : "Real Estate and Rental and Leasing",
    "Lessors of Nonresidential Buildings (except Miniwarehouses)" : "Real Estate and Rental and Leasing",
    "Lessors of Miniwarehouses and Self-Storage Units" : "Real Estate and Rental and Leasing",
    "Lessors of Other Real Estate Property" : "Real Estate and Rental and Leasing",
    "Offices of Real Estate Agents and Brokers" : "Real Estate and Rental and Leasing",
    "Activities Related to Real Estate" : "Real Estate and Rental and Leasing",
    "Residential Property Managers" : "Real Estate and Rental and Leasing",
    "Nonresidential Property Managers" : "Real Estate and Rental and Leasing",
    "Offices of Real Estate Appraisers" : "Real Estate and Rental and Leasing",
    "Other Activities Related to Real Estate" : "Real Estate and Rental and Leasing",
    "Automotive Equipment Rental and Leasing" : "Real Estate and Rental and Leasing",
    "Passenger Car Rental" : "Real Estate and Rental and Leasing",
    "Passenger Car Leasing" : "Real Estate and Rental and Leasing",
    "Truck, Utility Trailer, and RV (Recreational Vehicle) Rental and Leasing" : "Real Estate and Rental and Leasing",
    "Consumer Goods Rental" : "Real Estate and Rental and Leasing",
    "Consumer Electronics and Appliances Rental" : "Real Estate and Rental and Leasing",
    "Formal Wear and Costume Rental" : "Real Estate and Rental and Leasing",
    "Video Tape and Disc Rental" : "Real Estate and Rental and Leasing",
    "Home Health Equipment Rental" : "Real Estate and Rental and Leasing",
    "Recreational Goods Rental" : "Real Estate and Rental and Leasing",
    "All Other Consumer Goods Rental" : "Real Estate and Rental and Leasing",
    "General Rental Centers" : "Real Estate and Rental and Leasing",
    "Commercial and Industrial Machinery and Equipment Rental and Leasing" : "Real Estate and Rental and Leasing",
    "Commercial Air, Rail, and Water Transportation Equipment Rental and Leasing" : "Real Estate and Rental and Leasing",
    "Construction, Mining, and Forestry Machinery and Equipment Rental and Leasing" : "Real Estate and Rental and Leasing",
    "Office Machinery and Equipment Rental and Leasing" : "Real Estate and Rental and Leasing",
    "Other Commercial and Industrial Machinery and Equipment Rental and Leasing" : "Real Estate and Rental and Leasing",
    "Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)" : "Real Estate and Rental and Leasing",
    "Professional, Scientific, and Technical Services" : "Professional, Scientific, and Technical Services",
    "Legal Services" : "Professional, Scientific, and Technical Services",
    "Offices of Lawyers" : "Professional, Scientific, and Technical Services",
    "Offices of Notaries" : "Professional, Scientific, and Technical Services",
    "Title Abstract and Settlement Offices" : "Professional, Scientific, and Technical Services",
    "All Other Legal Services" : "Professional, Scientific, and Technical Services",
    "Accounting, Tax Preparation, Bookkeeping, and Payroll Services" : "Professional, Scientific, and Technical Services",
    "Offices of Certified Public Accountants" : "Professional, Scientific, and Technical Services",
    "Tax Preparation Services" : "Professional, Scientific, and Technical Services",
    "Payroll Services" : "Professional, Scientific, and Technical Services",
    "Other Accounting Services" : "Professional, Scientific, and Technical Services",
    "Architectural, Engineering, and Related Services" : "Professional, Scientific, and Technical Services",
    "Architectural Services" : "Professional, Scientific, and Technical Services",
    "Landscape Architectural Services" : "Professional, Scientific, and Technical Services",
    "Engineering Services" : "Professional, Scientific, and Technical Services",
    "Drafting Services" : "Professional, Scientific, and Technical Services",
    "Building Inspection Services" : "Professional, Scientific, and Technical Services",
    "Geophysical Surveying and Mapping Services" : "Professional, Scientific, and Technical Services",
    "Surveying and Mapping (except Geophysical) Services" : "Professional, Scientific, and Technical Services",
    "Testing Laboratories and Services" : "Professional, Scientific, and Technical Services",
    "Specialized Design Services" : "Professional, Scientific, and Technical Services",
    "Interior Design Services" : "Professional, Scientific, and Technical Services",
    "Industrial Design Services" : "Professional, Scientific, and Technical Services",
    "Graphic Design Services" : "Professional, Scientific, and Technical Services",
    "Other Specialized Design Services" : "Professional, Scientific, and Technical Services",
    "Computer Systems Design and Related Services" : "Professional, Scientific, and Technical Services",
    "Custom Computer Programming Services" : "Professional, Scientific, and Technical Services",
    "Computer Systems Design Services" : "Professional, Scientific, and Technical Services",
    "Computer Facilities Management Services" : "Professional, Scientific, and Technical Services",
    "Other Computer Related Services" : "Professional, Scientific, and Technical Services",
    "Management, Scientific, and Technical Consulting Services" : "Professional, Scientific, and Technical Services",
    "Administrative Management and General Management Consulting Services" : "Professional, Scientific, and Technical Services",
    "Human Resources Consulting Services" : "Professional, Scientific, and Technical Services",
    "Marketing Consulting Services" : "Professional, Scientific, and Technical Services",
    "Process, Physical Distribution, and Logistics Consulting Services" : "Professional, Scientific, and Technical Services",
    "Other Management Consulting Services" : "Professional, Scientific, and Technical Services",
    "Environmental Consulting Services" : "Professional, Scientific, and Technical Services",
    "Other Scientific and Technical Consulting Services" : "Professional, Scientific, and Technical Services",
    "Scientific Research and Development Services" : "Professional, Scientific, and Technical Services",
    "Research and Development in Nanotechnology" : "Professional, Scientific, and Technical Services",
    "Research and Development in Biotechnology (except Nanobiotechnology)" : "Professional, Scientific, and Technical Services",
    "Research and Development in the Physical, Engineering, and Life Sciences (except Nanotechnology and Biotechnology)" : "Professional, Scientific, and Technical Services",
    "Research and Development in the Social Sciences and Humanities" : "Professional, Scientific, and Technical Services",
    "Advertising, Public Relations, and Related Services" : "Professional, Scientific, and Technical Services",
    "Advertising Agencies" : "Professional, Scientific, and Technical Services",
    "Public Relations Agencies" : "Professional, Scientific, and Technical Services",
    "Media Buying Agencies" : "Professional, Scientific, and Technical Services",
    "Media Representatives" : "Professional, Scientific, and Technical Services",
    "Indoor and Outdoor Display Advertising" : "Professional, Scientific, and Technical Services",
    "Direct Mail Advertising" : "Professional, Scientific, and Technical Services",
    "Advertising Material Distribution Services" : "Professional, Scientific, and Technical Services",
    "Other Services Related to Advertising" : "Professional, Scientific, and Technical Services",
    "Other Professional, Scientific, and Technical Services" : "Professional, Scientific, and Technical Services",
    "Marketing Research and Public Opinion Polling" : "Professional, Scientific, and Technical Services",
    "Photography Studios, Portrait" : "Professional, Scientific, and Technical Services",
    "Commercial Photography" : "Professional, Scientific, and Technical Services",
    "Translation and Interpretation Services" : "Professional, Scientific, and Technical Services",
    "Veterinary Services" : "Professional, Scientific, and Technical Services",
    "All Other Professional, Scientific, and Technical Services" : "Professional, Scientific, and Technical Services",
    "Management of Companies and Enterprises" : "Management of Companies and Enterprises",
    "Offices of Bank Holding Companies" : "Management of Companies and Enterprises",
    "Offices of Other Holding Companies" : "Management of Companies and Enterprises",
    "Corporate, Subsidiary, and Regional Managing Offices" : "Management of Companies and Enterprises",
    "Administrative and Support and Waste Management and Remediation Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Office Administrative Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Facilities Support Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Employment Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Employment Placement Agencies" : "Administrative and Support and Waste Management and Remediation Services",
    "Executive Search Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Temporary Help Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Professional Employer Organizations" : "Administrative and Support and Waste Management and Remediation Services",
    "Business Support Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Document Preparation Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Telephone Answering Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Telemarketing Bureaus and Other Contact Centers" : "Administrative and Support and Waste Management and Remediation Services",
    "Private Mail Centers" : "Administrative and Support and Waste Management and Remediation Services",
    "Other Business Service Centers (including Copy Shops)" : "Administrative and Support and Waste Management and Remediation Services",
    "Collection Agencies" : "Administrative and Support and Waste Management and Remediation Services",
    "Credit Bureaus" : "Administrative and Support and Waste Management and Remediation Services",
    "Repossession Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Court Reporting and Stenotype Services" : "Administrative and Support and Waste Management and Remediation Services",
    "All Other Business Support Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Travel Arrangement and Reservation Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Travel Agencies" : "Administrative and Support and Waste Management and Remediation Services",
    "Tour Operators" : "Administrative and Support and Waste Management and Remediation Services",
    "Convention and Visitors Bureaus" : "Administrative and Support and Waste Management and Remediation Services",
    "All Other Travel Arrangement and Reservation Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Investigation and Security Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Investigation and Personal Background Check Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Security Guards and Patrol Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Armored Car Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Security Systems Services (except Locksmiths)" : "Administrative and Support and Waste Management and Remediation Services",
    "Locksmiths" : "Administrative and Support and Waste Management and Remediation Services",
    "Services to Buildings and Dwellings" : "Administrative and Support and Waste Management and Remediation Services",
    "Exterminating and Pest Control Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Janitorial Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Landscaping Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Carpet and Upholstery Cleaning Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Other Services to Buildings and Dwellings" : "Administrative and Support and Waste Management and Remediation Services",
    "Other Support Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Packaging and Labeling Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Convention and Trade Show Organizers" : "Administrative and Support and Waste Management and Remediation Services",
    "All Other Support Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Waste Collection" : "Administrative and Support and Waste Management and Remediation Services",
    "Solid Waste Collection" : "Administrative and Support and Waste Management and Remediation Services",
    "Hazardous Waste Collection" : "Administrative and Support and Waste Management and Remediation Services",
    "Other Waste Collection" : "Administrative and Support and Waste Management and Remediation Services",
    "Waste Treatment and Disposal" : "Administrative and Support and Waste Management and Remediation Services",
    "Hazardous Waste Treatment and Disposal" : "Administrative and Support and Waste Management and Remediation Services",
    "Solid Waste Landfill" : "Administrative and Support and Waste Management and Remediation Services",
    "Solid Waste Combustors and Incinerators" : "Administrative and Support and Waste Management and Remediation Services",
    "Other Nonhazardous Waste Treatment and Disposal" : "Administrative and Support and Waste Management and Remediation Services",
    "Remediation and Other Waste Management Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Remediation Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Materials Recovery Facilities" : "Administrative and Support and Waste Management and Remediation Services",
    "Septic Tank and Related Services" : "Administrative and Support and Waste Management and Remediation Services",
    "All Other Miscellaneous Waste Management Services" : "Administrative and Support and Waste Management and Remediation Services",
    "Educational Services" : "Educational Services",
    "Elementary and Secondary Schools" : "Educational Services",
    "Junior Colleges" : "Educational Services",
    "Colleges, Universities, and Professional Schools" : "Educational Services",
    "Business Schools and Computer and Management Training" : "Educational Services",
    "Business and Secretarial Schools" : "Educational Services",
    "Computer Training" : "Educational Services",
    "Professional and Management Development Training" : "Educational Services",
    "Technical and Trade Schools" : "Educational Services",
    "Cosmetology and Barber Schools" : "Educational Services",
    "Flight Training" : "Educational Services",
    "Apprenticeship Training" : "Educational Services",
    "Other Technical and Trade Schools" : "Educational Services",
    "Other Schools and Instruction" : "Educational Services",
    "Fine Arts Schools" : "Educational Services",
    "Sports and Recreation Instruction" : "Educational Services",
    "Language Schools" : "Educational Services",
    "Exam Preparation and Tutoring" : "Educational Services",
    "Automobile Driving Schools" : "Educational Services",
    "All Other Miscellaneous Schools and Instruction" : "Educational Services",
    "Educational Support Services" : "Educational Services",
    "Health Care and Social Assistance" : "Health Care and Social Assistance",
    "Offices of Physicians" : "Health Care and Social Assistance",
    "Offices of Physicians (except Mental Health Specialists)" : "Health Care and Social Assistance",
    "Offices of Physicians, Mental Health Specialists" : "Health Care and Social Assistance",
    "Offices of Dentists" : "Health Care and Social Assistance",
    "Offices of Other Health Practitioners" : "Health Care and Social Assistance",
    "Offices of Chiropractors" : "Health Care and Social Assistance",
    "Offices of Optometrists" : "Health Care and Social Assistance",
    "Offices of Mental Health Practitioners (except Physicians)" : "Health Care and Social Assistance",
    "Offices of Physical, Occupational and Speech Therapists, and Audiologists" : "Health Care and Social Assistance",
    "Offices of Podiatrists" : "Health Care and Social Assistance",
    "Offices of All Other Miscellaneous Health Practitioners" : "Health Care and Social Assistance",
    "Outpatient Care Centers" : "Health Care and Social Assistance",
    "Family Planning Centers" : "Health Care and Social Assistance",
    "Outpatient Mental Health and Substance Abuse Centers" : "Health Care and Social Assistance",
    "HMO Medical Centers" : "Health Care and Social Assistance",
    "Kidney Dialysis Centers" : "Health Care and Social Assistance",
    "Freestanding Ambulatory Surgical and Emergency Centers" : "Health Care and Social Assistance",
    "All Other Outpatient Care Centers" : "Health Care and Social Assistance",
    "Medical and Diagnostic Laboratories" : "Health Care and Social Assistance",
    "Medical Laboratories" : "Health Care and Social Assistance",
    "Diagnostic Imaging Centers" : "Health Care and Social Assistance",
    "Home Health Care Services" : "Health Care and Social Assistance",
    "Other Ambulatory Health Care Services" : "Health Care and Social Assistance",
    "Ambulance Services" : "Health Care and Social Assistance",
    "Blood and Organ Banks" : "Health Care and Social Assistance",
    "All Other Miscellaneous Ambulatory Health Care Services" : "Health Care and Social Assistance",
    "General Medical and Surgical Hospitals" : "Health Care and Social Assistance",
    "Psychiatric and Substance Abuse Hospitals" : "Health Care and Social Assistance",
    "Specialty (except Psychiatric and Substance Abuse) Hospitals" : "Health Care and Social Assistance",
    "Nursing Care Facilities (Skilled Nursing Facilities)" : "Health Care and Social Assistance",
    "Residential Intellectual and Developmental Disability, Mental Health, and Substance Abuse Facilities" : "Health Care and Social Assistance",
    "Residential Intellectual and Developmental Disability Facilities" : "Health Care and Social Assistance",
    "Residential Mental Health and Substance Abuse Facilities" : "Health Care and Social Assistance",
    "Continuing Care Retirement Communities and Assisted Living Facilities for the Elderly" : "Health Care and Social Assistance",
    "Continuing Care Retirement Communities" : "Health Care and Social Assistance",
    "Assisted Living Facilities for the Elderly" : "Health Care and Social Assistance",
    "Other Residential Care Facilities" : "Health Care and Social Assistance",
    "Individual and Family Services" : "Health Care and Social Assistance",
    "Child and Youth Services" : "Health Care and Social Assistance",
    "Services for the Elderly and Persons with Disabilities" : "Health Care and Social Assistance",
    "Other Individual and Family Services" : "Health Care and Social Assistance",
    "Community Food and Housing, and Emergency and Other Relief Services" : "Health Care and Social Assistance",
    "Community Food Services" : "Health Care and Social Assistance",
    "Temporary Shelters" : "Health Care and Social Assistance",
    "Other Community Housing Services" : "Health Care and Social Assistance",
    "Emergency and Other Relief Services" : "Health Care and Social Assistance",
    "Vocational Rehabilitation Services" : "Health Care and Social Assistance",
    "Child Care Services" : "Health Care and Social Assistance",
    "Arts, Entertainment, and Recreation" : "Arts, Entertainment, and Recreation",
    "Performing Arts Companies" : "Arts, Entertainment, and Recreation",
    "Theater Companies and Dinner Theaters" : "Arts, Entertainment, and Recreation",
    "Dance Companies" : "Arts, Entertainment, and Recreation",
    "Musical Groups and Artists" : "Arts, Entertainment, and Recreation",
    "Other Performing Arts Companies" : "Arts, Entertainment, and Recreation",
    "Spectator Sports" : "Arts, Entertainment, and Recreation",
    "Sports Teams and Clubs" : "Arts, Entertainment, and Recreation",
    "Racetracks" : "Arts, Entertainment, and Recreation",
    "Other Spectator Sports" : "Arts, Entertainment, and Recreation",
    "Promoters of Performing Arts, Sports, and Similar Events" : "Arts, Entertainment, and Recreation",
    "Promoters of Performing Arts, Sports, and Similar Events with Facilities" : "Arts, Entertainment, and Recreation",
    "Promoters of Performing Arts, Sports, and Similar Events without Facilities" : "Arts, Entertainment, and Recreation",
    "Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures" : "Arts, Entertainment, and Recreation",
    "Independent Artists, Writers, and Performers" : "Arts, Entertainment, and Recreation",
    "Museums, Historical Sites, and Similar Institutions" : "Arts, Entertainment, and Recreation",
    "Museums" : "Arts, Entertainment, and Recreation",
    "Historical Sites" : "Arts, Entertainment, and Recreation",
    "Zoos and Botanical Gardens" : "Arts, Entertainment, and Recreation",
    "Nature Parks and Other Similar Institutions" : "Arts, Entertainment, and Recreation",
    "Amusement Parks and Arcades" : "Arts, Entertainment, and Recreation",
    "Amusement and Theme Parks" : "Arts, Entertainment, and Recreation",
    "Amusement Arcades" : "Arts, Entertainment, and Recreation",
    "Gambling Industries" : "Arts, Entertainment, and Recreation",
    "Casinos (except Casino Hotels)" : "Arts, Entertainment, and Recreation",
    "Other Gambling Industries" : "Arts, Entertainment, and Recreation",
    "Other Amusement and Recreation Industries" : "Arts, Entertainment, and Recreation",
    "Golf Courses and Country Clubs" : "Arts, Entertainment, and Recreation",
    "Skiing Facilities" : "Arts, Entertainment, and Recreation",
    "Marinas" : "Arts, Entertainment, and Recreation",
    "Fitness and Recreational Sports Centers" : "Arts, Entertainment, and Recreation",
    "Bowling Centers" : "Arts, Entertainment, and Recreation",
    "All Other Amusement and Recreation Industries" : "Arts, Entertainment, and Recreation",
    "Accommodation and Food Services" : "Accommodation and Food Services",
    "Traveler Accommodation" : "Accommodation and Food Services",
    "Hotels (except Casino Hotels) and Motels" : "Accommodation and Food Services",
    "Casino Hotels" : "Accommodation and Food Services",
    "Bed-and-Breakfast Inns" : "Accommodation and Food Services",
    "All Other Traveler Accommodation" : "Accommodation and Food Services",
    "RV (Recreational Vehicle) Parks and Recreational Camps" : "Accommodation and Food Services",
    "RV (Recreational Vehicle) Parks and Campgrounds" : "Accommodation and Food Services",
    "Recreational and Vacation Camps (except Campgrounds)" : "Accommodation and Food Services",
    "Rooming and Boarding Houses, Dormitories, and Workers' Camps" : "Accommodation and Food Services",
    "Special Food Services" : "Accommodation and Food Services",
    "Food Service Contractors" : "Accommodation and Food Services",
    "Caterers" : "Accommodation and Food Services",
    "Mobile Food Services" : "Accommodation and Food Services",
    "Drinking Places (Alcoholic Beverages)" : "Accommodation and Food Services",
    "Restaurants and Other Eating Places" : "Accommodation and Food Services",
    "Full-Service Restaurants" : "Accommodation and Food Services",
    "Limited-Service Restaurants" : "Accommodation and Food Services",
    "Cafeterias, Grill Buffets, and Buffets" : "Accommodation and Food Services",
    "Snack and Nonalcoholic Beverage Bars" : "Accommodation and Food Services",
    "Other Services (except Public Administration)" : "Other Services (except Public Administration)",
    "Automotive Repair and Maintenance" : "Other Services (except Public Administration)",
    "General Automotive Repair" : "Other Services (except Public Administration)",
    "Specialized Automotive Repair" : "Other Services (except Public Administration)",
    "Automotive Body, Paint, and Interior Repair and Maintenance" : "Other Services (except Public Administration)",
    "Automotive Glass Replacement Shops" : "Other Services (except Public Administration)",
    "Automotive Oil Change and Lubrication Shops" : "Other Services (except Public Administration)",
    "Car Washes" : "Other Services (except Public Administration)",
    "All Other Automotive Repair and Maintenance" : "Other Services (except Public Administration)",
    "Electronic and Precision Equipment Repair and Maintenance" : "Other Services (except Public Administration)",
    "Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance" : "Other Services (except Public Administration)",
    "Personal and Household Goods Repair and Maintenance" : "Other Services (except Public Administration)",
    "Home and Garden Equipment Repair and Maintenance" : "Other Services (except Public Administration)",
    "Appliance Repair and Maintenance" : "Other Services (except Public Administration)",
    "Reupholstery and Furniture Repair" : "Other Services (except Public Administration)",
    "Footwear and Leather Goods Repair" : "Other Services (except Public Administration)",
    "Other Personal and Household Goods Repair and Maintenance" : "Other Services (except Public Administration)",
    "Personal Care Services" : "Other Services (except Public Administration)",
    "Barber Shops" : "Other Services (except Public Administration)",
    "Beauty Salons" : "Other Services (except Public Administration)",
    "Nail Salons" : "Other Services (except Public Administration)",
    "Diet and Weight Reducing Centers" : "Other Services (except Public Administration)",
    "Other Personal Care Services" : "Other Services (except Public Administration)",
    "Death Care Services" : "Other Services (except Public Administration)",
    "Funeral Homes and Funeral Services" : "Other Services (except Public Administration)",
    "Cemeteries and Crematories" : "Other Services (except Public Administration)",
    "Drycleaning and Laundry Services" : "Other Services (except Public Administration)",
    "Coin-Operated Laundries and Drycleaners" : "Other Services (except Public Administration)",
    "Drycleaning and Laundry Services (except Coin-Operated)" : "Other Services (except Public Administration)",
    "Linen Supply" : "Other Services (except Public Administration)",
    "Industrial Launderers" : "Other Services (except Public Administration)",
    "Other Personal Services" : "Other Services (except Public Administration)",
    "Pet Care (except Veterinary) Services" : "Other Services (except Public Administration)",
    "Photofinishing Laboratories (except One-Hour)" : "Other Services (except Public Administration)",
    "One-Hour Photofinishing" : "Other Services (except Public Administration)",
    "Parking Lots and Garages" : "Other Services (except Public Administration)",
    "All Other Personal Services" : "Other Services (except Public Administration)",
    "Religious Organizations" : "Other Services (except Public Administration)",
    "Grantmaking and Giving Services" : "Other Services (except Public Administration)",
    "Grantmaking Foundations" : "Other Services (except Public Administration)",
    "Voluntary Health Organizations" : "Other Services (except Public Administration)",
    "Other Grantmaking and Giving Services" : "Other Services (except Public Administration)",
    "Social Advocacy Organizations" : "Other Services (except Public Administration)",
    "Human Rights Organizations" : "Other Services (except Public Administration)",
    "Environment, Conservation and Wildlife Organizations" : "Other Services (except Public Administration)",
    "Other Social Advocacy Organizations" : "Other Services (except Public Administration)",
    "Civic and Social Organizations" : "Other Services (except Public Administration)",
    "Business, Professional, Labor, Political, and Similar Organizations" : "Other Services (except Public Administration)",
    "Business Associations" : "Other Services (except Public Administration)",
    "Professional Organizations" : "Other Services (except Public Administration)",
    "Labor Unions and Similar Labor Organizations" : "Other Services (except Public Administration)",
    "Political Organizations" : "Other Services (except Public Administration)",
    "Other Similar Organizations (except Business, Professional, Labor, and Political Organizations)" : "Other Services (except Public Administration)",
    "Private Households" : "Other Services (except Public Administration)",
    "Public Administration" : "Public Administration",
    "Executive, Legislative, and Other General Government Support" : "Public Administration",
    "Executive Offices" : "Public Administration",
    "Legislative Bodies" : "Public Administration",
    "Public Finance Activities" : "Public Administration",
    "Executive and Legislative Offices, Combined" : "Public Administration",
    "American Indian and Alaska Native Tribal Governments" : "Public Administration",
    "Other General Government Support" : "Public Administration",
    "Justice, Public Order, and Safety Activities" : "Public Administration",
    "Courts" : "Public Administration",
    "Police Protection" : "Public Administration",
    "Legal Counsel and Prosecution" : "Public Administration",
    "Correctional Institutions" : "Public Administration",
    "Parole Offices and Probation Offices" : "Public Administration",
    "Fire Protection" : "Public Administration",
    "Other Justice, Public Order, and Safety Activities" : "Public Administration",
    "Administration of Human Resource Programs" : "Public Administration",
    "Administration of Education Programs" : "Public Administration",
    "Administration of Public Health Programs" : "Public Administration",
    "Administration of Human Resource Programs (except Education, Public Health, and Veterans' Affairs Programs)" : "Public Administration",
    "Administration of Veterans' Affairs" : "Public Administration",
    "Administration of Environmental Quality Programs" : "Public Administration",
    "Administration of Air and Water Resource and Solid Waste Management Programs" : "Public Administration",
    "Administration of Conservation Programs" : "Public Administration",
    "Administration of Housing Programs, Urban Planning, and Community Development" : "Public Administration",
    "Administration of Housing Programs" : "Public Administration",
    "Administration of Urban Planning and Community and Rural Development" : "Public Administration",
    "Administration of Economic Programs" : "Public Administration",
    "Administration of General Economic Programs" : "Public Administration",
    "Regulation and Administration of Transportation Programs" : "Public Administration",
    "Regulation and Administration of Communications, Electric, Gas, and Other Utilities" : "Public Administration",
    "Regulation of Agricultural Marketing and Commodities" : "Public Administration",
    "Regulation, Licensing, and Inspection of Miscellaneous Commercial Sectors" : "Public Administration",
    "Space Research and Technology" : "Public Administration",
    "National Security and International Affairs" : "Public Administration",
    "National Security" : "Public Administration",
    "International Affairs" : "Public Administration",
    "Other Services" : "Other Services (except Public Administration)",
    "Total, All Industries" : "Total, All Industries",
    "Trade, Transportation, and Utilities" : "Generalistas",
    "Goods-Producing" : "Generalistas",
    "Education and Health Services" : "Generalistas",
    "Natural Resources and Mining" : "Generalistas",
    "Financial Activities" : "Generalistas",
    "Unclassified" : "Generalistas",
    "Professional and Business Services" : "Generalistas",
    "Service-Providing" : "Generalistas",
    "Leisure and Hospitality" : "Generalistas"}


    return setores